### PR TITLE
Neutral fraction datacomp update

### PR DESCRIPTION
**Pull request by wmfw23**
update some plots:

- Add various new data to HI and H2 fraction plots vs stellar mass (see [PR 80](https://github.com/SWIFTSIM/velociraptor-comparison-data/pull/80))
- Clarify selection functions in their captions
- Update HI and H2 cosmic density to plot comoving density not abundance (Omega)
-  add lots of data to H species evolution plots (see [PR 80](https://github.com/SWIFTSIM/velociraptor-comparison-data/pull/80))

### CODE REVIEW

**Comment by JBorrow** [comment]
Does this conflict with @EvgeniiChaikin's other MR? Can you two decide which one should be merged first?

**Comment by wmfw23** [comment]
I rebased to @EvgeniiChaikin 's plot removal PR, think the only thing we both touch in his new PR is some autoplotter captions; I'm adding lots of info about the observations, I'm indifferent to the order as I dont think it will be a complex rebase

**Comment by JBorrow** [comment]
Is there a reason you're directly using the text files here rather than HDF5ing them and using that?

**Comment by wmfw23** [comment]
I was following what was done for the  `colibre/scripts/load_sfh_data.py` and `colibre/scripts/star_formation_history.py`

**Comment by wmfw23** [comment]
currently the data itself isn't converted to hdf5 either

**Comment by JBorrow** [comment]
Okay, please don't do that again as we want the metadata primarily (so we can cite the right people) but given the time pressure I will merge this.

**Pull request merged**
