### PR TITLE
Added the EAGLE-12 SFR data ot COLIBRE pipeline

### PR DESCRIPTION
**Pull request by MatthieuSchaller**
@EvgeniiChaikin to help some comparisons. Anything else we want from EAGLE?

### CODE REVIEW

**Review by JBorrow — COMMENTED** [review]
Looks good to me, let's wait on @EvgeniiChaikin

**Comment by EvgeniiChaikin** [comment]
That all looks good!

Is there an SFH plot with this new curve?

**Comment by MatthieuSchaller** [comment]
star_formation_history

**Comment by EvgeniiChaikin** [comment]
Thanks! Wow, the EAGLE 12 is very similar to the EAGLE 25, and sometimes even above the 25. I didn't expect that.

**Comment by MatthieuSchaller** [comment]
The important aspect is that it's quite noisy as the box is rather small and that whole history is only a handful of objects.

**Pull request merged**
