### PR TITLE
Data on z>0 GSMF + BH plot limits

### PR DESCRIPTION
**Pull request by MatthieuSchaller**

### CODE REVIEW

**Comment by JBorrow** [comment]
We have changed the way that observational data is included (redshift-bracketed) on plots. Please see the example yaml at: https://velociraptor-python.readthedocs.io/en/latest/modules/velociraptor.autoplotter.html and ensure that you are using the latest version of velociraptor-python.

**Comment by MatthieuSchaller** [comment]
Ok. I had copied over from the COLIBRE side. Let me make the changes to both then.

**Comment by MatthieuSchaller** [comment]
Wait. That's not documented in your example yaml.

**Comment by JBorrow** [comment]
`observational_data_bracket_width: 0.1 - the width in log(a) of the window to plot observational
    data (defined below) within.`

**Comment by MatthieuSchaller** [comment]
doh...

**Comment by MatthieuSchaller** [comment]
Done. :)

**Pull request merged**
