### PR TITLE
Upgrade stellar-abundances plots

### PR DESCRIPTION
**Pull request by EvgeniiChaikin**
**Upgrade plots with stellar-abundances** 

- Add more colours to cycler to be able to distinguish between different datasets in metallicity plots
- Append plt lines only once (for labels)  in OFe plots 
- Include Gallazzi data in OFe plots and expand y ranges

@correac

### CODE REVIEW

**Comment by EvgeniiChaikin** [comment]
**New versions of the plots**

stellar_abundances_FeH_OFe

stellar_mass_star_mg_over_fe_100

stellar_mass_star_o_over_fe_100

**Comment by correac** [comment]
Hi @EvgeniiChaikin Thank you for those plots! We are including these changes with James now.

**Comment by MatthieuSchaller** [comment]
What is the status of this?

**Comment by correac** [comment]
This is solved. More detailed abundances plots are done by the morphology pipeline now. The integrated [O/Fe], [Mg/Fe] vs. stellar mass plots are already in the current pipeline and look ok.

**Comment by MatthieuSchaller** [comment]
So should this be merged or closed?

**Comment by EvgeniiChaikin** [comment]
This needs to be merged. The PR fixes a few small bugs and adds new observational data to two plots.

**Pull request merged**
