### PR TITLE
Update gas and star metallicity plots

### PR DESCRIPTION
**Pull request by EvgeniiChaikin**
Follows #113 from @wmfw23

Example: http://swift.dur.ac.uk/COLIBREPlots/chaikin/individual_runs/HAWK/L006N188/z0.0_01_REFERENCE/

### CODE REVIEW

**Comment by JBorrow** [comment]
Can you please rebase, you've both changed a lot of the same lines to similar but subtly different things. If there is something that you don't want me to merge please ensure it's closed - I will only review for code quality as I can't keep track of everything cold-gas related.

**Comment by EvgeniiChaikin** [comment]
This branch should now be ready

**Comment by wmfw23** [comment]
> Can you please rebase, you've both changed a lot of the same lines to similar but subtly different things. If there is something that you don't want me to merge please ensure it's closed - I will only review for code quality as I can't keep track of everything cold-gas related.

Hey Josh, the PRs have been useful for @EvgeniiChaikin & I to iterate on the functionality aspects, but I've been using WIP to indicate ongoing, maybe this is just gitlab terminology as I see you can still merge it. Given we're iterating a lot right now, and may get a list of new things to add in all three repos, maybe we can flag better when is a good time for you to review code quality?

**Comment by JBorrow** [comment]
Okay - I see. If that's the case please assign one of you two. I'll look at things when they're assigned to me.

**Comment by JBorrow** [comment]
Is this ready to be merged?

**Comment by EvgeniiChaikin** [comment]
In my opinion, yes. I have been continuously using this branch for the past few days and haven't encountered any crashes or bugs.

**Pull request merged**
