### PR TITLE
Updated baryon fraction and GSMF Flamingo

### PR DESCRIPTION
**Pull request by jemme07**
Updated baryon fraction and GSMF auto_plotter configs for a better visualisations for flamingo. Now only plot baryon fraction  for field haloes.

### CODE REVIEW

**Comment by JBorrow** [comment]
Happy to merge with @Moyoxkit's approval.

**Comment by MatthieuSchaller** [comment]
That's all good. We need the change for flamingo. 
Let me port the changes to the gas fractions also to XL.

**Comment by MatthieuSchaller** [comment]
ah it will have to be a separate MR.

**Comment by MatthieuSchaller** [comment]
Also, that's Jaime. :)

**Comment by JBorrow** [comment]
@jemme07 Can you please set your GitHub 'name' to your name? It's getting hard to remember people's usernames!

**Pull request merged**
