### PR TITLE
Add script to plot the birth densities

### PR DESCRIPTION
**Pull request by MatthieuSchaller**

### CODE REVIEW

**Comment by JBorrow** [comment]
This plot will be super messy during comparisons; I will come back to you early next week with a better version for the new pipeline.

**Comment by MatthieuSchaller** [comment]
Yeah, thought so. That's where I stopped as the other rho-Z feedback ones are even more messy. I guess for the comparisons we want the same as for the rho-T planes.

**Comment by MatthieuSchaller** [comment]
I guess this can be closer?

**Comment by JBorrow** [comment]
yep thanks

**Pull request closed without merging**
