### PR TITLE
Add H_2 mass function data

### PR DESCRIPTION
**Pull request by MatthieuSchaller**

### CODE REVIEW

**Comment by JBorrow** [comment]
Can you also rev the commit of the obesrvational data if this is newly added?

**Comment by MatthieuSchaller** [comment]
Don't know what you mean.

**Comment by JBorrow** [comment]
The observational_data git submodule needs to have its commit value revved when we add new obs data. If that's the case here, we'll need to do that or it might cause issues, so:

cd observational_data
git pull origin master
cd ..
git commit -m "Revved commit" observational_data

**Comment by MatthieuSchaller** [comment]
Right. I think the data is there as it is in colibre but I'll do that nevertheless

**Pull request merged**
