### PR TITLE
Some cold gas updates

### PR DESCRIPTION
**Pull request by MatthieuSchaller**
That infamous factor of 2.

### CODE REVIEW

**Comment by MatthieuSchaller** [comment]
Also:

 - Add M_H2 / (M_HI + M_H2) vs. M_*
 - Use a single section for all the cold gas relation plots

**Comment by JBorrow** [comment]
Do all of these make use of the adaptive binning? Not sure from the plots you've shown that they do.

**Comment by MatthieuSchaller** [comment]
As far as I can tell, the scripts demand an adaptive binning. Could the odd-looking plots be due to zeros being problematic?

**Comment by JBorrow** [comment]
Ah yes if the average in that bin is zero then I suppose what we see (missing bins) is expected behaviour

**Comment by MatthieuSchaller** [comment]
Is there a way to fix that or should I just not plot medians?

**Comment by JBorrow** [comment]
Well you could create a mask that only includes certain galaxies (e.g. those with > some_value H_2 mass) or we can just live with it.

**Comment by MatthieuSchaller** [comment]
But we want zeros to be shown.

**Comment by JBorrow** [comment]
In that case it is fine as-is, I suppose the median of those lines at that position _should_ be zero

**Comment by MatthieuSchaller** [comment]
Then that's ready to go I think.

**Pull request merged**
