### PR TITLE
Add/update cold gas & dust plots

### PR DESCRIPTION
**Pull request by EvgeniiChaikin**
Hi @jtrayford @JBorrow 

A couple of updates in this PR:

**Major**
- add  temperature-density phase plot colour-coded by **dust** mass fraction to the colibre config
- Copy (cold) gas relation section from eagle XL

**Minor**
- add dust mass function plot with adaptive binning (after having discussed it with @jtrayford)
- show two more BN98 plots on the webpage (Joop wanted to have an M*/M_BN98 vs M* plot on the webpage)
- Fix the median lines in SNII density plot (this is a tiny fix)
- Change the name of one of the parameters in `description.html `because SWIFT now outputs it with a different name
- Format/clean up the temperature_density_dust script
- Fix typo in `colibre/auto_plotter/stellar_mass_halo_mass.yml`
- Remove pycache from the repository.

**Example of the new Temperature Density section**

Screenshot from 2020-11-12 16-16-41

**Example of the new Cold Gas Relations section**

Screenshot from 2020-11-12 16-16-58

**Example of the new Gas Mass Function section**

Screenshot from 2020-11-12 16-18-06

P.S. I didn't anticipate that this PR would become so big. I can break it into several pieces if needed
P.S. Note that many things (e.g. registration.py) were

### CODE REVIEW

**Comment by JBorrow** [comment]
As there's no new code here if @jtrayford is happy with it i'll merge

**Comment by EvgeniiChaikin** [comment]
@JBorrow perfect! Note that I purposely haven't fixed the label in the dust mass function plot(s) because I saw you had done that already in [THIS PR](https://github.com/SWIFTSIM/pipeline-configs/pull/51)

As an additional test, I have just run this branch on cosma7. An example of a whole webpage is [HERE](http://swift.dur.ac.uk/COLIBREPlots/chaikin/individual_runs/With_AGN/L006N188/With_BH_mergers/z1.0_EOS_gamma2_T8e3_n1e2_T20/)

**Comment by JBorrow** [comment]
Excellent, thanks. The rho-T plots look quite nice with plasma, better than I expected!

**Comment by EvgeniiChaikin** [comment]
I am now (again) looking at the plots above @jtrayford maybe it'd better for colibre to decrease the lower limit for` stellar mass` in all cold-gas-relations plots from **1e9** to **1e6** Msolar? What do you think?

**Comment by wmfw23** [comment]
Hi, the plots look good, happy to merge! RE lowering the M* limit - the data is for galaxies with mass > 1e9, so I'm worried lowering by 4 dex may lead to an unfair comparison on the panels where stellar mass isn't on the axes.

**Comment by EvgeniiChaikin** [comment]
Thanks, James! Then I think this branch can indeed be merged. I have nothing else to add.

**Pull request merged**
