### PR TITLE
Update plots/captions in colibre webpage

### PR DESCRIPTION
**Pull request by EvgeniiChaikin**
**1. Why this PR**
request

**2. Changes**

See [this issue](https://github.com/SWIFTSIM/pipeline-configs/issues/67)

- stellar birth density plots
- stellar mass function halo mass function plots
- star formation rate plots

### CODE REVIEW

**Comment by EvgeniiChaikin** [comment]
**One more change:**

In all stellar mass vs halo mass plots (both EAGLE-XL and COLIBRE configs), I extended the X-axis to **lower** halo masses so that **all** objects can be seen in the plots.


**Example:**

stellar_mass_halo_mass_M200_all_100

Without this change, we would only see the objects with halo masses greater than `1e8 Msun`, which would be incomplete information.

**Comment by JBorrow** [comment]
Apologies, you're going to need to fix the conflicts. Do you have a full page I can look at with these changes too?

**Comment by EvgeniiChaikin** [comment]
@JBorrow 

Just a short summary of the current version of this PR

- I merged in the latest master
- the detached version of the comparison-data repository is updated, which now includes the latest changes to the EAGLE2015 and Berhoozi2019 data
- As discussed some time ago, there is no need to assign a certain SFR to the galaxies below the passive-fraction threshold. (that is why there is a small change in `registration.py`) 
- The changes in `autoplotter/stellar_mass_halo_mass.yml look horrible`. But actually, I just rearranged certain blocks of code so that the figures appear on the web-page in the order Joop was asking for. I also extended the lower limit of the halo mass in all plots with the name signatures `stellar_mass_halo_mass_*_all_30/100` so that these plots show all objects that a run may possibly have
- In `config.yml`, I added the word **birth** in the caption of stellar-birth-density figures so that it is more clear that we are talking about the birth densities and not about something else
- The new web-page will look like [THIS](http://swift.dur.ac.uk/COLIBREPlots/chaikin/individual_runs/With_AGN/L006N188/With_BH_mergers/z5.0_fkin05_EOSn1e2_vkick25_dtyoung01/)

**Comment by JBorrow** [comment]
Thanks!

**Pull request merged**
