### PR TITLE
Add plot of metallicity difference between active and passive galaxies

### PR DESCRIPTION
**Pull request by robjmcgibbon**
sim_passive_active_metallicity_difference

I will update the submodule link once https://github.com/SWIFTSIM/velociraptor-comparison-data/pull/190 is merged

### CODE REVIEW

**Comment by MatthieuSchaller** [comment]
@EvgeniiChaikin are you looking at this or should I?

**Comment by EvgeniiChaikin** [comment]
I will update and merge this PR after https://github.com/SWIFTSIM/velociraptor-comparison-data/pull/190 is merged.

**Review by EvgeniiChaikin — COMMENTED** [review]
Hi @robjmcgibbon 

My recent update includes:
- rebase to the current master branch
- rewrite the code that loads observational data 
- update the version of the submodule this branch is referring to
- Add `stellar' before `metallicity' in the file names and plot description, to distinguish it from `gas-phase metallicity'.

This script now looks good to me and I am not planning to add any further changes.

**Comment by EvgeniiChaikin** [comment]
Most changes relative to your version of the script can be viewed here: https://github.com/SWIFTSIM/pipeline-configs/pull/270/commits/9da4c7c0d37e02dc538827f1a095a1bb3581d89f

**Review by EvgeniiChaikin — APPROVED** [review]

**Pull request merged**
